CREATE TABLE PART_B AS(
With full_part_b as (
SELECT *, '2021' AS "YEAR" FROM PART_B_2021
UNION
SELECT *, '2022' AS "YEAR" FROM PART_B_2022
UNION
SELECT *, '2023' AS "YEAR" FROM PART_B_2023
)

SELECT * FROM FULL_PART_B
);

CREATE OR REPLACE TABLE MODEL_READY.PART_B AS(
SELECT 
    RNDRNG_NPI AS "NPI",
    RNDRNG_PRVDR_CRDNTLS AS "CREDENTIALS",
    RNDRNG_PRVDR_ST1 AS "STREET_ADDRESS_L1",
    RNDRNG_PRVDR_ST2 AS "STREET_ADDRESS_L2",
    RNDRNG_PRVDR_CITY AS "CITY",
    RNDRNG_PRVDR_STATE_ABRVTN AS "STATE",
    RNDRNG_PRVDR_ZIP5 AS "ZIP",
    RNDRNG_PRVDR_RUCA AS "RUCA_CODE",
    RNDRNG_PRVDR_TYPE AS "PROVIDER_TYPE",
    COALESCE(CAST(TOT_HCPCS_CDS AS INT), 0) AS "UNIQUE_HCPCS_CODES",
    COALESCE(CAST(TOT_BENES AS INT), 0) AS "MEDICARE_BENEFICIARIES",
    COALESCE(CAST(TOT_SRVCS AS INT), 0) AS "TOTAL_SERVICES",
    COALESCE(CAST(TOT_SBMTD_CHRG AS DECIMAL(12,2)), 0) AS "TOTAL_SUBMITTED_CHARGES",
    COALESCE(CAST(TOT_MDCR_ALOWD_AMT AS DECIMAL(12,2)), 0) AS "TOTAL_BENEFICIARY_RESPOSIBILITY",
    COALESCE(CAST(TOT_MDCR_PYMT_AMT AS DECIMAL(12,2)), 0) AS "TOTAL_MEDICARE_REIMBURSEMENT",
    COALESCE(CAST(TOT_MDCR_STDZD_AMT AS DECIMAL(12,2)), 0) AS "TOTAL_STD_MEDICARE_REIMBURSEMENT",
    CASE 
        WHEN DRUG_SPRSN_IND = '*' THEN 'Y'
        WHEN DRUG_SPRSN_IND = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "DRUG_SUPPRESSION",
    COALESCE(CAST(DRUG_TOT_HCPCS_CDS AS INT), 0) AS "DRUG_UNIQUE_HCPCS_CODES",
    COALESCE(CAST(DRUG_TOT_BENES AS INT), 0) AS "DRUG_MEDICARE_BENEFICIARIES", 
    COALESCE(CAST(DRUG_TOT_SRVCS AS INT), 0) AS "DRUG_TOTAL_SERVICES",
    COALESCE(CAST(DRUG_SBMTD_CHRG AS DECIMAL(12,2)), 0) AS "DRUG_SUBMITTED_CHARGES",
    COALESCE(CAST(DRUG_MDCR_ALOWD_AMT AS DECIMAL(12,2)), 0) AS "DRUG_BENEFICIARY_RESPOSIBILITY",
    COALESCE(CAST(DRUG_MDCR_PYMT_AMT AS DECIMAL(12,2)), 0) AS "DRUG_MEDICARE_REIMBURSEMENT",
    COALESCE(CAST(DRUG_MDCR_STDZD_AMT AS DECIMAL(12,2)), 0) AS "DRUG_STD_MEDICARE_REIMBURSEMENT",
    CASE 
        WHEN MED_SPRSN_IND = '*' THEN 'Y'
        WHEN MED_SPRSN_IND = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "MED_SUPPRESSION",
    COALESCE(CAST(MED_TOT_HCPCS_CDS AS INT), 0) AS "MED_UNIQUE_HCPCS_CODES",
    COALESCE(CAST(MED_TOT_BENES AS INT), 0) AS "MED_MEDICARE_BENEFICIARIES", 
    COALESCE(CAST(MED_TOT_SRVCS AS INT), 0) AS "MED_TOTAL_SERVICES",
    COALESCE(CAST(MED_SBMTD_CHRG AS DECIMAL(12,2)), 0) AS "MED_SUBMITTED_CHARGES",
    COALESCE(CAST(MED_MDCR_ALOWD_AMT AS DECIMAL(12,2)), 0) AS "MED_BENEFICIARY_RESPOSIBILITY",
    COALESCE(CAST(MED_MDCR_PYMT_AMT AS DECIMAL(12,2)), 0) AS "MED_MEDICARE_REIMBURSEMENT",
    COALESCE(CAST(MED_MDCR_STDZD_AMT AS DECIMAL(12,2)), 0) AS "MED_STD_MEDICARE_REIMBURSEMENT",
    COALESCE(CAST(BENE_AVG_AGE AS INT), 0) AS "BENEFICIARY_AVG_AGE",
    COALESCE(CAST(BENE_AGE_LT_65_CNT AS INT), 0) AS "LT_60_COUNT",
    COALESCE(CAST(BENE_AGE_65_74_CNT AS INT), 0) AS "65_74_COUNT",
    COALESCE(CAST(BENE_AGE_75_84_CNT AS INT), 0) AS "75-84_COUNT",
    COALESCE(CAST(BENE_AGE_GT_84_CNT AS INT), 0) AS "GT_84_COUNT",
    COALESCE(CAST(BENE_FEML_CNT AS INT), 0) AS "F_COUNT",
    COALESCE(CAST(BENE_MALE_CNT AS INT), 0) AS "M_COUNT",
    COALESCE(CAST(BENE_RACE_WHT_CNT AS INT), 0) AS "WHT_COUNT",
    COALESCE(CAST(BENE_RACE_BLACK_CNT AS INT), 0) AS "BLK_COUNT",
    COALESCE(CAST(BENE_RACE_API_CNT AS INT), 0) AS "API_COUNT",
    COALESCE(CAST(BENE_RACE_HSPNC_CNT AS INT), 0) AS "HISP_COUNT",
    COALESCE(CAST(BENE_RACE_NATIND_CNT AS INT), 0) AS "NATIVE_COUNT",
    COALESCE(CAST(BENE_RACE_OTHR_CNT AS INT), 0) AS "OTHER_COUNT",
    COALESCE(CAST(BENE_DUAL_CNT AS INT), 0) AS "CARE_CAID_RECIEVERS",
    COALESCE(CAST(BENE_NDUAL_CNT AS INT), 0) AS "CARE_ONLY_RECIEVERS",
    COALESCE(CAST(BENE_CC_BH_ADHD_OTHCD_V1_PCT AS INT), 0) AS "V1_PCT_ADHD_AND_SIMILAR",
    COALESCE(CAST(BENE_CC_BH_ALCOHOL_DRUG_V1_PCT AS INT), 0) AS "V1_PCT_ALC_DRUG",
    COALESCE(CAST(BENE_CC_BH_TOBACCO_V1_PCT AS INT), 0) AS "V1_PCT_TOBACCO",
    COALESCE(CAST(BENE_CC_BH_ALZ_NONALZDEM_V2_PCT AS INT), 0) AS "V2_PCT_ALZHEIMERS_DEMENTIA",
    COALESCE(CAST(BENE_CC_BH_ANXIETY_V1_PCT AS INT), 0) AS "V1_PCT_ANXIETY",
    COALESCE(CAST(BENE_CC_BH_BIPOLAR_V1_PCT AS INT), 0) AS "V1_PCT_BIPOLAR",
    COALESCE(CAST(BENE_CC_BH_MOOD_V2_PCT AS INT), 0) AS "V2_PCT_DEPRESSIVE_MOOD",
    COALESCE(CAST(BENE_CC_BH_DEPRESS_V1_PCT AS INT), 0) AS "V1_PCT_DEPRESSIVE_EFFECT",
    COALESCE(CAST(BENE_CC_BH_PD_V1_PCT AS INT), 0) AS "V1_PCT_PERSONALITY_DISORDERS",
    COALESCE(CAST(BENE_CC_BH_PTSD_V1_PCT AS INT), 0) AS "V1_PCT_PTSD",
    COALESCE(CAST(BENE_CC_BH_SCHIZO_OTHPSY_V1_PCT AS INT), 0) AS "V1_PCT_SCHIZO_PSYCHOTIC",
    COALESCE(CAST(BENE_CC_PH_ASTHMA_V2_PCT AS INT), 0) AS "V2_PCT_ASTHMA",
    COALESCE(CAST(BENE_CC_PH_AFIB_V2_PCT AS INT), 0) AS "V2_PCT_AFIB",
    COALESCE(CAST(BENE_CC_PH_CANCER6_V2_PCT AS INT), 0) AS "V2_PCT_6_CANCERS",
    COALESCE(CAST(BENE_CC_PH_CKD_V2_PCT AS INT), 0) AS "V2_PCT_KIDNEY",
    COALESCE(CAST(BENE_CC_PH_COPD_V2_PCT AS INT), 0) AS "V2_PCT_COPD",
    COALESCE(CAST(BENE_CC_PH_DIABETES_V2_PCT AS INT), 0) AS "V2_PCT_DIABETES",
    COALESCE(CAST(BENE_CC_PH_HF_NONIHD_V2_PCT AS INT), 0) AS "V2_PCT_HEART_FAILURE_NONIHD",
    COALESCE(CAST(BENE_CC_PH_HYPERLIPIDEMIA_V2_PCT AS INT), 0) AS "V2_PCT_HYPERLIPIDEMIA",
    COALESCE(CAST(BENE_CC_PH_HYPERTENSION_V2_PCT AS INT), 0) AS "V2_PCT_HYPERTENSION",
    COALESCE(CAST(BENE_CC_PH_ISCHEMICHEART_V2_PCT AS INT), 0) AS "V2_PCT_ISCHEMIC_HEARTH",
    COALESCE(CAST(BENE_CC_PH_OSTEOPOROSIS_V2_PCT AS INT), 0) AS "V2_PCT_OSTEOPOROSIS",
    COALESCE(CAST(BENE_CC_PH_PARKINSON_V2_PCT AS INT), 0) AS "V2_PCT_PARKINSONS",
    COALESCE(CAST(BENE_CC_PH_ARTHRITIS_V2_PCT AS INT), 0) AS "V2_PCT_ARTHRITIS",
    COALESCE(CAST(BENE_CC_PH_STROKE_TIA_V2_PCT AS INT), 0) AS "V2_PCT_STROKE",
    COALESCE(CAST(BENE_AVG_RISK_SCRE AS FLOAT), 0) AS "PATIENT_AVG_RISK_SCORE",
    TO_DATE("YEAR" || '-01-01', 'YYYY-MM-DD') AS "YEAR"
    
FROM 
    PART_B
WHERE RNDRNG_PRVDR_CNTRY = 'US' AND RNDRNG_PRVDR_MDCR_PRTCPTG_IND = 'Y'
);

CREATE TABLE PART_D AS(
With full_part_d as (
SELECT *, '2021' AS "YEAR" FROM PART_D_2021
UNION
SELECT *, '2022' AS "YEAR" FROM PART_D_2022
UNION
SELECT *, '2023' AS "YEAR" FROM PART_D_2023
)

SELECT * FROM FULL_PART_D
);

CREATE OR REPLACE TABLE MODEL_READY.PART_D AS(
SELECT 
    PRSCRBR_NPI AS "NPI",
    PRSCRBR_CRDNTLS AS "CREDENTIALS",
    PRSCRBR_ST1 AS "STREET_ADDRESS_L1",
    PRSCRBR_ST2 AS "STREET_ADDRESS_L2",
    PRSCRBR_CITY AS "CITY",
    PRSCRBR_STATE_ABRVTN AS "STATE",
    PRSCRBR_ZIP5 AS "ZIP",
    PRSCRBR_RUCA AS "RUCA_CODE",
    PRSCRBR_TYPE AS "PROVIDER_TYPE",
    PRSCRBR_TYPE_SRC AS "PROVIDER_TYPE_SOURCE", 
    COALESCE(CAST(TOT_CLMS AS INT), 0) AS "TOTAL_CLAIMS", 
    COALESCE(CAST(TOT_30DAY_FILLS AS DECIMAL(12,2)), 0) AS "TOTAL_30DAY_FILLS", 
    COALESCE(CAST(TOT_DRUG_CST AS DECIMAL(12,2)), 0) AS "TOTAL_DRUG_COST", 
    COALESCE(CAST(TOT_DAY_SUPLY AS INT), 0) AS "TOTAL_DAY_SUPPLY", 
    COALESCE(CAST(TOT_BENES AS INT), 0) AS "TOTAL_BENEFICIARIES", 
    CASE 
        WHEN GE65_SPRSN_FLAG = '*' THEN 'Y'
        WHEN GE65_SPRSN_FLAG = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "GE65_SUPPRESSION", 
    COALESCE(CAST(GE65_TOT_CLMS AS INT), 0) AS "GE65_TOTAL_CLAIMS", 
    COALESCE(CAST(GE65_TOT_30DAY_FILLS AS DECIMAL(12,2)), 0) AS "GE65_TOTAL_30DAY_FILLS", 
    COALESCE(CAST(GE65_TOT_DRUG_CST AS DECIMAL(12,2)), 0) AS "GE65_TOTAL_DRUG_COST", 
    COALESCE(CAST(GE65_TOT_DAY_SUPLY AS INT), 0) AS "GE65_TOTAL_DAY_SUPPLY", 
    CASE 
        WHEN GE65_BENE_SPRSN_FLAG = '*' THEN 'Y'
        WHEN GE65_BENE_SPRSN_FLAG = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "GE65_BENE_SUPPRESSION", 
    COALESCE(CAST(GE65_TOT_BENES AS INT), 0) AS "GE65_TOTAL_BENEFICIARIES", 
    CASE 
        WHEN BRND_SPRSN_FLAG = '*' THEN 'Y'
        WHEN BRND_SPRSN_FLAG = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "BRAND_SUPPRESSION", 
    COALESCE(CAST(BRND_TOT_CLMS AS INT), 0) AS "BRAND_TOTAL_CLAIMS", 
    COALESCE(CAST(BRND_TOT_DRUG_CST AS DECIMAL(12,2)), 0) AS "BRAND_TOTAL_DRUG_COST", 
    CASE 
        WHEN GNRC_SPRSN_FLAG = '*' THEN 'Y'
        WHEN GNRC_SPRSN_FLAG = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "GENERIC_SUPPRESSION", 
    COALESCE(CAST(GNRC_TOT_CLMS AS INT), 0) AS "GENERIC_TOTAL_CLAIMS", 
    COALESCE(CAST(GNRC_TOT_DRUG_CST AS DECIMAL(10,2)), 0) AS "GENERIC_TOTAL_DRUG_COST", 
    CASE 
        WHEN OTHR_SPRSN_FLAG = '*' THEN 'Y'
        WHEN OTHR_SPRSN_FLAG = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "OTHER_SUPPRESSION", 
    COALESCE(CAST(OTHR_TOT_CLMS AS INT), 0) AS "OTHER_TOTAL_CLAIMS", 
    COALESCE(CAST(OTHR_TOT_DRUG_CST AS DECIMAL(12,2)), 0) AS "OTHER_TOTAL_DRUG_COST", 
    CASE 
        WHEN MAPD_SPRSN_FLAG = '*' THEN 'Y'
        WHEN MAPD_SPRSN_FLAG = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "MAPD_SUPPRESSION", 
    COALESCE(CAST(MAPD_TOT_CLMS AS INT), 0) AS "MAPD_TOTAL_CLAIMS", 
    COALESCE(CAST(MAPD_TOT_DRUG_CST AS DECIMAL(12,2)), 0) AS "MAPD_TOTAL_DRUG_COST", 
    CASE 
        WHEN PDP_SPRSN_FLAG = '*' THEN 'Y'
        WHEN PDP_SPRSN_FLAG = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "PDP_SUPPRESSION", 
    COALESCE(CAST(PDP_TOT_CLMS AS INT), 0) AS "PDP_TOTAL_CLAIMS", 
    COALESCE(CAST(PDP_TOT_DRUG_CST AS DECIMAL(12,2)), 0) AS "PDP_TOTAL_DRUG_COST", 
    CASE 
        WHEN LIS_SPRSN_FLAG = '*' THEN 'Y'
        WHEN LIS_SPRSN_FLAG = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "LIS_SUPPRESSION", 
    COALESCE(CAST(LIS_TOT_CLMS AS INT), 0) AS "LIS_TOTAL_CLAIMS", 
    COALESCE(CAST(LIS_DRUG_CST AS DECIMAL(12,2)), 0) AS "LIS_DRUG_COST", 
    CASE 
        WHEN NONLIS_SPRSN_FLAG = '*' THEN 'Y'
        WHEN NONLIS_SPRSN_FLAG = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "NONLIS_SUPPRESSION", 
    COALESCE(CAST(NONLIS_TOT_CLMS AS INT), 0) AS "NONLIS_TOTAL_CLAIMS", 
    COALESCE(CAST(NONLIS_DRUG_CST AS DECIMAL(12,2)), 0) AS "NONLIS_DRUG_COST", 
    COALESCE(CAST(OPIOID_TOT_CLMS AS INT), 0) AS "OPIOID_TOTAL_CLAIMS", 
    COALESCE(CAST(OPIOID_TOT_DRUG_CST AS DECIMAL(12,2)), 0) AS "OPIOID_TOTAL_DRUG_COST", 
    COALESCE(CAST(OPIOID_TOT_SUPLY AS INT), 0) AS "OPIOID_TOTAL_SUPPLY", 
    COALESCE(CAST(OPIOID_TOT_BENES AS INT), 0) AS "OPIOID_TOTAL_BENEFICIARIES", 
    COALESCE(CAST(OPIOID_PRSCRBR_RATE AS FLOAT), 0) AS "OPIOID_PRESCRIBER_RATE", 
    COALESCE(CAST(OPIOID_LA_TOT_CLMS AS INT), 0) AS "OPIOID_LA_TOTAL_CLAIMS", 
    COALESCE(CAST(OPIOID_LA_TOT_DRUG_CST AS DECIMAL(10,2)), 0) AS "OPIOID_LA_TOTAL_DRUG_COST", 
    COALESCE(CAST(OPIOID_LA_TOT_SUPLY AS INT), 0) AS "OPIOID_LA_TOTAL_SUPPLY", 
    COALESCE(CAST(OPIOID_LA_TOT_BENES AS INT), 0) AS "OPIOID_LA_TOTAL_BENEFICIARIES", 
    COALESCE(CAST(OPIOID_LA_PRSCRBR_RATE AS FLOAT), 0) AS "OPIOID_LA_PRESCRIBER_RATE", 
    COALESCE(CAST(ANTBTC_TOT_CLMS AS INT), 0) AS "ANTIBIOTIC_TOTAL_CLAIMS",
    COALESCE(CAST(ANTBTC_TOT_DRUG_CST AS DECIMAL(12,2)), 0) AS "ANTIBIOTIC_TOTAL_DRUG_COST", 
    COALESCE(CAST(ANTBTC_TOT_BENES AS INT), 0) AS "ANTIBIOTIC_TOTAL_BENEFICIARIES", 
    CASE 
        WHEN ANTPSYCT_GE65_SPRSN_FLAG = '*' THEN 'Y'
        WHEN ANTPSYCT_GE65_SPRSN_FLAG = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "ANTIPSYCHOTIC_GE65_SUPPRESSION", 
    COALESCE(CAST(ANTPSYCT_GE65_TOT_CLMS AS INT), 0) AS "ANTIPSYCHOTIC_GE65_TOTAL_CLAIMS", 
    COALESCE(CAST(ANTPSYCT_GE65_TOT_DRUG_CST AS DECIMAL(10,2)), 0) AS "ANTIPSYCHOTIC_GE65_TOTAL_DRUG_COST", 
    CASE 
        WHEN ANTPSYCT_GE65_BENE_SUPRSN_FLAG = '*' THEN 'Y'
        WHEN ANTPSYCT_GE65_BENE_SUPRSN_FLAG = '#' THEN 'Y/COUNTER'
        ELSE 'N'
    END AS "ANTIPSYCHOTIC_GE65_BENE_SUPPRESSION", 
    COALESCE(CAST(ANTPSYCT_GE65_TOT_BENES AS INT), 0) AS "ANTIPSYCHOTIC_GE65_TOTAL_BENEFICIARIES", 
    COALESCE(CAST(BENE_AVG_AGE AS FLOAT), 0) AS "BENEFICIARY_AVG_AGE",
    COALESCE(CAST(BENE_AGE_LT_65_CNT AS INT), 0) AS "LT_65_COUNT",
    COALESCE(CAST(BENE_AGE_65_74_CNT AS INT), 0) AS "65_74_COUNT",
    COALESCE(CAST(BENE_AGE_75_84_CNT AS INT), 0) AS "75_84_COUNT",
    COALESCE(CAST(BENE_AGE_GT_84_CNT AS INT), 0) AS "GT_84_COUNT",
    COALESCE(CAST(BENE_FEML_CNT AS INT), 0) AS "F_COUNT",
    COALESCE(CAST(BENE_MALE_CNT AS INT), 0) AS "M_COUNT",
    COALESCE(CAST(BENE_RACE_WHT_CNT AS INT), 0) AS "WHT_COUNT",
    COALESCE(CAST(BENE_RACE_BLACK_CNT AS INT), 0) AS "BLK_COUNT",
    COALESCE(CAST(BENE_RACE_API_CNT AS INT), 0) AS "API_COUNT",
    COALESCE(CAST(BENE_RACE_HSPNC_CNT AS INT), 0) AS "HISP_COUNT",
    COALESCE(CAST(BENE_RACE_NATIND_CNT AS INT), 0) AS "NATIVE_COUNT",
    COALESCE(CAST(BENE_RACE_OTHR_CNT AS INT), 0) AS "OTHER_COUNT",
    COALESCE(CAST(BENE_DUAL_CNT AS INT), 0) AS "CARE_CAID_RECEIVERS",
    COALESCE(CAST(BENE_NDUAL_CNT AS INT), 0) AS "CARE_ONLY_RECEIVERS",
    COALESCE(CAST(BENE_AVG_RISK_SCRE AS FLOAT), 0) AS "PATIENT_AVG_RISK_SCORE",
    TO_DATE("YEAR" || '-01-01', 'YYYY-MM-DD') AS "YEAR"
    
FROM 
    PART_D
WHERE PRSCRBR_CNTRY = 'US'
);

SELECT 
    CAST(NPI AS INT) AS "NPI",
    GENERAL,
    SPECIALTY,
    TO_DATE(NULLIF(DOB, ''), 'YYYYMMDD') AS "DOB",
    ADDRESS,
    CITY,
    STATE,
    CAST(ZIP AS TEXT) AS "ZIP",
    EXCLTYPE AS "EXCLUSION_TYPE",
    TO_DATE(CAST(excldate AS TEXT), 'YYYYMMDD') AS "EXCLUSION_DATE",
    TO_DATE(NULLIF(CAST(WAIVERDATE AS TEXT), '0'), 'YYYYMMDD') AS "WAIVER_DATE",
    NULLIF(WVRSTATE, '') AS "WAIVER_STATE",
    -- Map exclusion codes to descriptions
    CASE 
        -- Mandatory Exclusions (Section 1128(a))
        WHEN EXCLTYPE = '1128a1' THEN 'Conviction of program-related crimes (Mandatory - Min 5 years)'
        WHEN EXCLTYPE = '1128a2' THEN 'Conviction relating to patient abuse or neglect (Mandatory - Min 5 years)'
        WHEN EXCLTYPE = '1128a3' THEN 'Felony conviction relating to health care fraud (Mandatory - Min 5 years)'
        WHEN EXCLTYPE = '1128a4' THEN 'Felony conviction relating to controlled substance (Mandatory - Min 5 years)'
        
        -- Permissive Exclusions (Section 1128(b))
        WHEN EXCLTYPE = '1128b1' THEN 'Misdemeanor conviction relating to health care fraud (Permissive - Baseline 3 years)'
        WHEN EXCLTYPE = '1128b2' THEN 'Conviction relating to obstruction of investigation/audit (Permissive - Baseline 3 years)'
        WHEN EXCLTYPE = '1128b3' THEN 'Misdemeanor conviction relating to controlled substance (Permissive - Baseline 3 years)'
        WHEN EXCLTYPE = '1128b4' THEN 'License revocation, suspension, or surrender (Permissive - Min: Period imposed by state)'
        WHEN EXCLTYPE = '1128b5' THEN 'Exclusion/suspension under federal or state health care program (Permissive - Min: Period imposed by program)'
        WHEN EXCLTYPE = '1128b6' THEN 'Excessive charges, unnecessary services, or substandard care (Permissive - Min 1 year)'
        WHEN EXCLTYPE = '1128b7' THEN 'Fraud, kickbacks, and other prohibited activities (Permissive - No minimum)'
        WHEN EXCLTYPE = '1128b8' THEN 'Entities controlled by sanctioned individual (Permissive - Same as individual exclusion)'
        WHEN EXCLTYPE = '1128b9' THEN 'Failure to disclose required information (Permissive - No minimum)'
        WHEN EXCLTYPE = '1128b10' THEN 'Failure to supply requested information on subcontractors/suppliers (Permissive - No minimum)'
        WHEN EXCLTYPE = '1128b11' THEN 'Failure to supply payment information (Permissive - No minimum)'
        WHEN EXCLTYPE = '1128b12' THEN 'Failure to grant immediate access (Permissive - No minimum)'
        WHEN EXCLTYPE = '1128b13' THEN 'Failure to take corrective action (Permissive - No minimum)'
        WHEN EXCLTYPE = '1128b14' THEN 'Default on health education loan/scholarship obligations (Permissive - Until resolved)'
        WHEN EXCLTYPE = '1128b15' THEN 'Individuals controlling sanctioned entity (Permissive - Same as entity exclusion)'
        WHEN EXCLTYPE = '1128b16' THEN 'Making false statements/misrepresentations (Permissive - No minimum)'
        
        -- Section 1156 Exclusions
        WHEN EXCLTYPE = '1156' THEN 'Failure to meet QIO statutory obligations for medically necessary services (Min 1 year)'
        
        -- Breach-Related Exclusions
        WHEN EXCLTYPE = 'BRCH SA' THEN 'Breach of Settlement Agreement'
        WHEN EXCLTYPE = 'BRCH CIA' THEN 'Breach of Corporate Integrity Agreement'
        
        -- System Codes
        WHEN EXCLTYPE = 'EXCLTYPE' THEN 'General Exclusion Type Identifier'
        
        -- Default case for unmapped codes
        ELSE 'Unknown Exclusion Code: ' || EXCLTYPE
    END AS "EXCLUSION_DESCRIPTION"
FROM EXCLUSION_LIST;

CREATE TABLE MODEL_READY.providers as (

with combo_d as (
SELECT * ILIKE 'PRSCRBR%', '2021' as YEAR FROM PART_D_2021
UNION
SELECT * ILIKE 'PRSCRBR%','2022' as YEAR FROM PART_D_2022
UNION
SELECT * ILIKE 'PRSCRBR%','2023' as YEAR FROM PART_D_2023
),
combo_b as (
SELECT * ILIKE 'RNDRNG%', '2021' as YEAR FROM PART_B_2021
UNION
SELECT * ILIKE 'RNDRNG%', '2022' as YEAR FROM PART_B_2022
UNION
SELECT * ILIKE 'RNDRNG%', '2023' as YEAR FROM PART_B_2023
),

--SELECT * FROM COMBO where PRSCRBR_NPI = 1386254753;
redux_1 as(
SELECT DISTINCT 
    PRSCRBR_NPI as "NPI",
    PRSCRBR_ENT_CD as "ENTITY_TYPE"
FROM 
    combo_d
),

redux_2 as(
SELECT DISTINCT 
    RNDRNG_NPI as "NPI",
    RNDRNG_PRVDR_ENT_CD as "ENTITY_TYPE"
FROM 
    combo_b
),

final as (
SELECT * FROM redux_1
UNION
SELECT * FROM redux_2
)


SELECT DISTINCT 
    *
FROM 
    final
    );


